name: Build

on:
  workflow_call:
    inputs:
      codeql:
        type: boolean

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            preset: windows-ci
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Configure and Build (Windows)
        if: matrix.preset == 'windows-ci'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64
          IF %ERRORLEVEL% NEQ 0 exit /B %ERRORLEVEL%
          cl /Bv
          set CXX=cl
          set CC=cl
          cmake --preset ${{ matrix.preset }}
          IF %ERRORLEVEL% NEQ 0 exit /B %ERRORLEVEL%
          cmake --build --preset ${{ matrix.preset }} -- -k0
      - uses: actions/upload-artifact@v7
        with:
          name: vcpkg
          path: D:/a/vcpkg-tool/vcpkg-tool/out/build
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg-root
